# Worksheet-0
# Name: Image Gautam
# University Student Number: 2407757
# College ID: np03cs4a230193


# Exercise on function

In [1]:
#Unit Conversion Program
def convert_units(conversion_type, value):
    if conversion_type == 1:
        return value * 3.28084
    elif conversion_type == 2:
        return value / 3.28084
    elif conversion_type == 3:
        return value * 2.20462
    elif conversion_type == 4:
        return value / 2.20462
    elif conversion_type == 5:
        return value * 0.264172
    elif conversion_type == 6:
        return value / 0.264172

print("1: meters->feet  \n2: feet->meters")
print("3: kg->lbs      \n4: lbs->kg")
print("5: liters->gallons \n6: gallons->liters")

try:
    c = int(input("Enter conversion type: "))
    v = float(input("Enter value: "))
    print("Converted:", convert_units(c,v))
except:
    print("Invalid input")


1: meters->feet  
2: feet->meters
3: kg->lbs      
4: lbs->kg
5: liters->gallons 
6: gallons->liters
Enter conversion type: 1
Enter value: 2
Converted: 6.56168


In [2]:
# Sum, Average, Max, Min from user list
def find_sum(nums):
    return sum(nums)

def find_avg(nums):
    return sum(nums)/len(nums)

def find_max(nums):
    return max(nums)

def find_min(nums):
    return min(nums)

try:
    numbers=input("Enter numbers separated by space: ")
    nums=[float(x) for x in numbers.split()]
    print("Sum:",find_sum(nums))
    print("Average:",find_avg(nums))
    print("Max:",find_max(nums))
    print("Min:",find_min(nums))
except:
    print("Invalid input")


Enter numbers separated by space: 1 2
Sum: 3.0
Average: 1.5
Max: 2.0
Min: 1.0


# Exercise on List manupulation

In [3]:
#Extract every other element
lst=[1,2,3,4,5,6]
print(lst[::2])


[1, 3, 5]


In [4]:
# Sublist
lst=[1,2,3,4,5,6]
print(lst[2:5])


[3, 4, 5]


In [5]:
#Reverse list
lst=[1,2,3,4,5]
print(lst[::-1])


[5, 4, 3, 2, 1]


In [6]:
#Remove first and last
lst=[1,2,3,4,5]
print(lst[1:-1])


[2, 3, 4]


In [7]:
# First N elements
lst=[1,2,3,4,5]
print(lst[:3])


[1, 2, 3]


In [8]:
#Last N elements
lst=[1,2,3,4,5]
print(lst[-2:])


[4, 5]


In [9]:
# Reverse skipping
lst=[1,2,3,4,5,6]
print(lst[-2::-2])


[5, 3, 1]


# Exercise on Nested List

In [10]:
# Flatten Nested List
def flatten(lst):
    r=[]
    for i in lst:
        if isinstance(i,list):
            r+=flatten(i)
        else:
            r.append(i)
    return r

print(flatten([[1,2],[3,4],[5]]))


[1, 2, 3, 4, 5]


In [11]:
# Access nested element
lst=[[1,2,3],[4,5,6],[7,8,9]]
print(lst[1][2])


6


In [12]:
#Sum nested list
def sum_nested(lst):
    s=0
    for i in lst:
        if isinstance(i,list):
            s+=sum_nested(i)
        else:
            s+=i
    return s

print(sum_nested([[1,2],[3,[4,5]],6]))


21


In [13]:
#Remove element
def remove_element(lst,val):
    r=[]
    for i in lst:
        if isinstance(i,list):
            r.append(remove_element(i,val))
        elif i!=val:
            r.append(i)
    return r

print(remove_element([[1,2],[3,2],[4,5]],2))


[[1], [3], [4, 5]]


In [14]:
# Max in nested list
def find_max(lst):
    m=float('-inf')
    for i in lst:
        if isinstance(i,list):
            m=max(m,find_max(i))
        else:
            m=max(m,i)
    return m

print(find_max([[1,2],[3,[4,5]],6]))


6


In [15]:
# Count occurrences
def count_occ(lst,val):
    c=0
    for i in lst:
        if isinstance(i,list):
            c+=count_occ(i,val)
        elif i==val:
            c+=1
    return c

print(count_occ([[1,2],[2,3],[2,4]],2))


3


In [16]:
# Deep flatten
def deep_flatten(lst):
    r=[]
    for i in lst:
        if isinstance(i,list):
            r+=deep_flatten(i)
        else:
            r.append(i)
    return r

print(deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))


[1, 2, 3, 4, 5, 6, 7, 8]


In [17]:
#Average nested list
def flatten(lst):
    r=[]
    for i in lst:
        if isinstance(i,list):
            r+=flatten(i)
        else:
            r.append(i)
    return r

f=flatten([[1,2],[3,4],[5,6]])
print(sum(f)/len(f))


3.5


# Basic Vector and Matrix Operation with Numpy

In [18]:
import numpy as np

# 1. Initialize an empty array with size 2x2
arr1 = np.empty((2,2))
print("1. Empty array (2x2):\n", arr1)

# 2. Initialize an all one array with size 4x2
arr2 = np.ones((4,2))
print("\n2. Ones array (4x2):\n", arr2)

# 3. Array filled with a specific value
arr3 = np.full((3,3), 7)
print("\n3. Array filled with value 7:\n", arr3)

# 4. Zeros array with same shape and type as arr2
arr4 = np.zeros_like(arr2)
print("\n4. Zeros like arr2:\n", arr4)

# 5. Ones array with same shape and type as arr4
arr5 = np.ones_like(arr4)
print("\n5. Ones like arr4:\n", arr5)

# 6. Convert list to numpy array
new_list = [1,2,3,4]
arr6 = np.array(new_list)
print("\n6. List converted to numpy array:\n", arr6)

1. Empty array (2x2):
 [[2.24622362e-315 0.00000000e+000]
 [6.59737730e-310 3.70563463e-317]]

2. Ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with value 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like arr2:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

5. Ones like arr4:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

6. List converted to numpy array:
 [1 2 3 4]


In [19]:
import numpy as np

# 1. Array with values from 10 to 49
arr1 = np.arange(10,50)
print("1. Values from 10 to 49:\n", arr1)

# 2. Create 3x3 matrix with values 0 to 8
arr2 = np.arange(9).reshape(3,3)
print("\n2. 3x3 matrix from 0 to 8:\n", arr2)

# 3. Create 3x3 identity matrix
arr3 = np.eye(3)
print("\n3. Identity matrix:\n", arr3)

# 4. Random array of size 30 and find mean
arr4 = np.random.random(30)
print("\n4. Random array:\n", arr4)
print("Mean:", arr4.mean())

# 5. 10x10 random array with min and max
arr5 = np.random.random((10,10))
print("\n5. Random 10x10 array:\n", arr5)
print("Minimum:", arr5.min())
print("Maximum:", arr5.max())

# 6. Zero array of size 10 and replace 5th element with 1
arr6 = np.zeros(10)
arr6[4] = 1
print("\n6. Zero array with 5th element replaced:\n", arr6)

# 7. Reverse an array
arr7 = np.array([1,2,0,0,4,0])
print("\n7. Reversed array:\n", arr7[::-1])

# 8. 2D array with 1 on border and 0 inside
arr8 = np.ones((5,5))
arr8[1:-1,1:-1] = 0
print("\n8. Border array:\n", arr8)

# 9. 8x8 checkerboard pattern
arr9 = np.zeros((8,8), dtype=int)
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print("\n9. Checkerboard pattern:\n", arr9)

1. Values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array:
 [0.50949392 0.0764246  0.41277836 0.15351354 0.7526793  0.34235867
 0.83103206 0.67690834 0.58371622 0.16801942 0.62154011 0.35924756
 0.03599728 0.77454285 0.91392671 0.83137595 0.30218677 0.88449039
 0.61350733 0.38687954 0.56387576 0.68713832 0.91956589 0.44836665
 0.07697851 0.72730138 0.0488372  0.27256815 0.63372049 0.25525895]
Mean: 0.49547434180356337

5. Random 10x10 array:
 [[0.27507533 0.70924429 0.30690414 0.15250703 0.02300641 0.70144296
  0.71648495 0.26318722 0.9842057  0.1922153 ]
 [0.54556116 0.99450971 0.73702252 0.16333674 0.78133108 0.47361426
  0.36829119 0.42289964 0.20094302 0.48916537]
 [0.08608948 0.37372056 0.86691158 0.60035179 0.88467891 0.15753367
  0.6037158  0.89131144 0.07621

In [20]:
# NumPy ranges
import numpy as np
print(np.arange(10,50))
print(np.arange(9).reshape(3,3))
print(np.eye(3))


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
#Random array stats
import numpy as np
a=np.random.random(30)
print(a.mean())

b=np.random.random((10,10))
print(b.min(),b.max())


0.5002974701425342
0.051691601441486656 0.9890768902429141


# Array Operation

In [22]:
#Array operations
x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print(x+y)
print(x-y)
print(x*3)
print(x**2)
print(np.dot(v, w))
print(np.dot(x, v))
print(np.dot(x, y))
print(np.concatenate((x, y), axis=0))

vw_column = np.column_stack((v, w))
print(vw_column)


[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 3  6]
 [ 9 15]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


In [23]:
print("\nTrying to concatenate x and v:")
try:
    print(np.concatenate((x, v)))
except Exception as e:
    print("Error:", e)

print("\nExplanation:")
print("x is a 2D array (2x2) while v is a 1D array.")
print("NumPy cannot concatenate arrays with different dimensions.")
print("To concatenate them, v must be reshaped to match x's dimensions.")


Trying to concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Explanation:
x is a 2D array (2x2) while v is a 1D array.
NumPy cannot concatenate arrays with different dimensions.
To concatenate them, v must be reshaped to match x's dimensions.


# Matrix Operation

In [24]:
#Matrix operations
A=np.array([[3,4],[7,8]])
B=np.array([[5,3],[2,1]])


In [25]:
#Prove A * A^-1 = I

A_inv = np.linalg.inv(A)

print("\nInverse of A:")
print(A_inv)

identity_check = np.dot(A, A_inv)

print("\nA * A^-1 :")
print(identity_check)


Inverse of A:
[[-2.    1.  ]
 [ 1.75 -0.75]]

A * A^-1 :
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [26]:
#Prove AB ≠ BA


AB = np.dot(A, B)
BA = np.dot(B, A)

print("\nA * B =")
print(AB)

print("\nB * A =")
print(BA)

print("\nAre AB and BA equal?")
print(np.array_equal(AB, BA))


A * B =
[[23 13]
 [51 29]]

B * A =
[[36 44]
 [13 16]]

Are AB and BA equal?
False


In [27]:
#Prove (AB)^T = B^T A^T


AB_T = (AB).T
BT_AT = np.dot(B.T, A.T)

print("\n(AB)^T =")
print(AB_T)

print("\nB^T * A^T =")
print(BT_AT)

print("\nAre they equal?")
print(np.array_equal(AB_T, BT_AT))


(AB)^T =
[[23 51]
 [13 29]]

B^T * A^T =
[[23 51]
 [13 29]]

Are they equal?
True


In [28]:
# Solve Linear Equations using Matrix Method
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])

B_eq = np.array([[-1],
                 [-3],
                 [9]])

print("\nCoefficient Matrix A:")
print(A_eq)

print("\nConstant Matrix B:")
print(B_eq)


Coefficient Matrix A:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

Constant Matrix B:
[[-1]
 [-3]
 [ 9]]


In [29]:
# Solve using Inverse Method
A_eq_inv = np.linalg.inv(A_eq)

X = np.dot(A_eq_inv, B_eq)

print("\nSolution using Inverse Method (X = A^-1 B):")
print("x =", X[0][0])
print("y =", X[1][0])
print("z =", X[2][0])


Solution using Inverse Method (X = A^-1 B):
x = 2.0
y = 1.0
z = -2.0


In [30]:
# Solve directly using np.linalg.inv()
X2 = np.linalg.inv(A_eq).dot(B_eq)

print("\nSolution using np.linalg.inv function:")
print("x =", X2[0][0])
print("y =", X2[1][0])
print("z =", X2[2][0])


Solution using np.linalg.inv function:
x = 2.0
y = 1.0
z = -2.0


# How fast is Numpy

In [31]:
#NumPy vs Python speed
import time

size=1000000
a=list(range(size))
b=list(range(size))

start=time.time()
c=[a[i]+b[i] for i in range(size)]
print("Python time:",time.time()-start)

x=np.arange(size)
y=np.arange(size)

start=time.time()
z=x+y
print("NumPy time:",time.time()-start)


Python time: 0.06752467155456543
NumPy time: 0.001928567886352539
